version: '3'

services:
    front-end:
        build: client
        ports:
        - "4200:4200"
        volumes:
        - ./pwa:/app
        - /app/node_modules/
        env_file:
        - ./.env
        
volumes:
    mongo_benchmarking_platform:
    nodemodules: