version: '3'

services:
    front-end:
        build: .
        ports:
        - "4200:4200"
        volumes:
        - ./src:/benchmarking_platform/src
        - ./.env:/benchmarking_platform/.env
        env_file:
        - ./.env
        
volumes:
    mongo_benchmarking_platform:
    nodemodules: